name: Supernova <> Figma Token sync
on:
  # Any branch you want
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync_tokens:
    runs-on: ubuntu-latest
    steps:
      # Check out repository under $GITHUB_WORKSPACE, so the CLI utility can read it
      - uses: actions/checkout@v3

      # Setup node to use with CLI. 14+ is required
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      
      # Install Supernova CLI
      - name: Install Supernova CLI dependency
        run: npm install --g @supernovaio/cli

      # Sync tokens
      - name: Synchronize tokens with Supernova 
        run: supernova sync-tokens \
        --apiKey=${{ sn.Lc1VEVk8pJmshmUjdVpI7YxyU7WNT8J1T5IqSJiG2a61c8wdCBrEBGysGWSu7E0OOba1BRELe7xXkWYW3e47StfE52CPGO0Q}} \
        --designSystemId=21933 \
        --tokenFilePath="${{ github.workspace }}/data/tokens.json" \
        --configFilePath="${{ github.workspace }}/data/supernova.settings.json" \
